version: '3'
networks:
  esusu-net:
    driver: bridge
services:
  postgres:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    restart: always
    environment:      
      POSTGRES_USER: esusu
      POSTGRES_PASSWORD: esusu      
      POSTGRES_DB: esusu
    ports:
        - 54322:5432
    networks:
        - esusu-net
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres-data: